platform :ios, '6.1'
pod 'AFNetworking', '1.3.3'
pod 'SDWebImage'
pod 'MTLog'
pod 'RegexKitLite'
pod 'SVProgressHUD', '1.0'
pod 'ZAActivityBar'
pod 'JSQSystemSoundPlayer', '~>1.5'
#pod 'JSMessagesViewController'
pod 'ALActionBlocks'
pod 'NSString+Emoji'
pod 'FMDB'
pod 'MCSwipeTableViewCell'
pod 'SSKeychain'
pod 'RETableViewManager', '1.5.14'
pod 'CTAssetsPickerController', :git => "https://github.com/wujichao/CTAssetsPickerController.git"
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'Qiniu', :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-1.x'
pod 'JSPatch'
pod 'Mantle', '1.5.4'
pod 'Objective-LevelDB'