platform :ios, '6.1'
pod 'AFNetworking', '1.3.3'
pod 'SDWebImage'
pod 'MTLog'
pod 'UI7Kit'
pod 'HMSegmentedControl'
pod 'RegexKitLite'
pod 'SVProgressHUD', '~> 1.0'
pod 'ZAActivityBar'
pod 'JSQSystemSoundPlayer', '~>1.5'
#pod 'JSMessagesViewController'
pod 'ALActionBlocks'
pod 'NSString+Emoji'
pod 'SDWebImage-ProgressView'
pod 'FMDB'
pod 'JDStatusBarNotification'
pod 'MCSwipeTableViewCell'
pod 'SSKeychain'
pod 'RETableViewManager'
pod 'CTAssetsPickerController', :git => "https://github.com/wujichao/CTAssetsPickerController.git"
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'SDURLCache', :git => 'https://github.com/wujichao/SDURLCache.git'
pod 'Qiniu', :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-1.x'